### ISSUE TITLE
Paste oddities.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#1024]
### Issue:

When pasting content in Aztec, the some of the visual styling shown in visual mode is not properly maintained when switching to HTML mode and back.

Some of the styling is even changed.

### Tasks:

- [x] After pasting text that ends with a certain text color (as shown below), switching to HTML mode and back should not change the color for all of the content.
- [x] When pasting content from Safari, paste the HTML in order to maintain the styling.
- [x] Allow apps to discard certain HTML elements or attributes when pasting HTML into Aztec.
- [x] When pasting attributed text, drop all non-supported styles.

### How to reproduce:

![pasteissues](https://user-images.githubusercontent.com/1836005/44210126-09d71380-a13c-11e8-8b70-c7551fedfc25.gif)

**Comment by diegoreymendez** [comment]
Closing.  We can open a more specific issue if necessary.
