### ISSUE TITLE
Formatters: remove need for zero-width spaces.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#414]
<h3>Description:</h3>

Currently, our formatters require zero-width spaces so that they can apply styles (such as header, blockquote, list) to an empty range of text.

The problem with adding these characters is that we must remove them too, once they're no longer necessary.  This has not been the case so far.

We need to remove the need to have those characters inserted to begin with.

<h3>Details:</h3>

Some research has shown that modifying the typing attributes has an impact on how the text view lays out its contents.  This is the direction that should enable us to draw blockquotes, lists, etc without really adding any content.

The problem with this approach is that `NSLayoutManager` does not have access to the `typingAttributes` of its parent `UITextView`.

There are some hints online that these attributes are actually accessible through a private property.  Search for `typingAttributes` in [these NextStep sources](http://svn.gna.org/svn/gnustep/libs/gui/trunk/Headers/AppKit/NSLayoutManager.h).

<h3>Proposal:</h3>

- Make sure styles are applied to typingAttributes whenever the line is empty (if there's a newline character, the line is NOT empty).
- Consider drawing the bullet items for lists in `TextView` instead of `LayoutManager`.
- Make sure whenever a formatter enables or disables a style, the line where the caret is placed is redrawn (we probably need to redraw al involved lines when there's a selection instead of a caret).
- Remove zero-width space markers everywhere.

### Child issues:
- [x] Nuke ZeroWidth Space from HeaderFormatter - #419. 
- [x] Nuke ZeroWidth Space from PreFormatter - #420.
- [x] Nuke ZeroWidth Space from TextList - #421.
- [x] Nuke ZeroWidth Space from BlockquoteFormatter - #422.

**Comment by SergioEstevao** [comment]
I tried to remove the need of this zero-width spaces two times already, and the issues was not the access to the attributes, but to be able to make the NSLayouManager to trigger any draw method.

What I found in my tests, is that until you write something the layoumanager is not triggered in any way to draw. If we find a method that triggers drawing then we can draw the markers.

**Comment by diegoreymendez** [comment]
That's good info @SergioEstevao - I'll try to investigate in that direction.

**Comment by diegoreymendez** [comment]
One alternative could be to draw the custom background elements in the `TextView` instead of in the layout manager, since the TextView already has access to the typing attributes, and doesn't need a glyph range to trigger its own draw methods.

**Comment by SergioEstevao** [comment]
I tried to override the draw method on TextView, but was not successful to trigger it by changing the typing attributes, we may need to force it...

**Comment by diegoreymendez** [comment]
@SergioEstevao - We could force a redraw whenever a formatter enables a style.  Do you think that could do?

**Comment by diegoreymendez** [comment]
Updated the proposal.

**Comment by diegoreymendez** [comment]
For the record, we did remove ZWSs, but we did not change the way in which lists are drawn.  We're simply adding a trailing `\n` whenever the caret is at EOF.
