### ISSUE TITLE
[Master Issues] Remove DOM tree.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#492]
Migrate to only using NSAttributedString.

More information will be added here after defining the work plan.

### Tasks:

- [x] Unhook the dom syncrhonization
- [x] Adapt ParagraphStyle to hold all paragraph styles in a single array
- [x] Adapt ParagraphStyle so that each style has HTML attribute info
- [x] Write NSAttributedString -> Node output converter.
  - [x] Unit Tests
  - [x] Nuke internal enums
  - [x] Newline Support
- [x] Remove EditContext from the code.
- [x] Remove old logic and unused unit tests.

**Comment by diegoreymendez** [comment]
Closing this for now.  We'll be treating any remaining work in more atomic issues.
