### ISSUE TITLE
[Master Issues] New Format Bar

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/AztecEditor-iOS#501]
We need to update the format bar to match the latest design updates.

![initial - back to paragraph - typed - next line 2x](https://user-images.githubusercontent.com/4780/26969335-4e87333c-4cfd-11e7-8be9-0975a90d9bab.jpg)

### Tasks:

- [x] Allow for collapsing / expanding set of items
- [x] Animate collapse / expansion
- [x] Remember collapsed / expanded state when bar is re-shown
- [x] Update Heading icon when heading / paragraph style changes
- [x] Show popover for heading selection for regular width size class
- [x] Add analytics
- [x] RTL support

**Comment by frosty** [comment]
Yep!

**Comment by diegoreymendez** [comment]
@frosty - Can you set the milestone?  (I use it to track progress)

Thanks!
